from django.urls import path
from . import views
urlpatterns = [
    path("", views.home, name="home"),
    path("signup/", views.signup, name="signup"),
    path("jobs/", views.job_listing,name="jobs"),
    path("job/<int:id>", views.job_detail,name="job_detail"),
    path('create-job/', views.create_or_edit_job, name='create_job'),
    path('job/<int:id>/edit/', views.create_or_edit_job, name='edit_job'),
    path('job/<int:id>/delete/', views.delete_job, name='delete_job'),
    path("dashboard/companies", views.companies, name="companies"),
    path("dashboard/Locations", views.locations, name="locations"),
    path("dashboard/Catgories", views.categories, name="categoreis"),
    path("dashboard/contact", views.contact_view, name="contact_veiw"),
    path("addcompany/", views.create_or_edit_company, name="add_company"),
    path("dashboard/company/<int:id>/",
         views.company_detail, name="company_detail"),
    path("dashboard/company/<int:id>/edit/",
         views.create_or_edit_company, name="edit_company"),
    path("dashboard/company/<int:id>/delete/",
         views.delete_company, name="delete_company"),
    path("addlocation/", views.create_or_edit_location, name="add_location"),
    path("dashboard/location/<int:id>/",
         views.location_detail, name="location_detail"),
    path("dashboard/location/<int:id>/edit/",
         views.create_or_edit_location, name="edit_location"),
    path("dashboard/location/<int:id>/delete/",
         views.delete_location, name="delete_location"),
    path("addcategory/", views.create_or_edit_category, name="add_category"),
    path("dashboard/category/<int:id>/",
         views.category_detail, name="category_detail"),
    path("dashboard/category/<int:id>/edit/",
         views.create_or_edit_category, name="edit_category"),
    path("dashboard/category/<int:id>/delete/",
         views.delete_category, name="delete_category"),
    path("contact/", views.contact,name="contact"),
    path("dashboard/contact/<int:id>/",
         views.contact_detail, name="contact_detail"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path('404/', views.custom_404, name='404'),
    path('apply/<int:job_id>/', views.apply_for_job, name='apply_for_job'),
    path("dashboard/applications", views.application_list_view, name="applications"),
    path("dashboard/application/<int:id>/",
         views.application_detail, name="application_detail"),

]
