# Generated by Django 5.0.1 on 2024-09-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
