# Generated by Django 5.0.1 on 2024-09-13 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0004_remove_job_company_remove_job_job_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('job_type', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('CT', 'Contract'), ('IN', 'Internship'), ('RM', 'Remote'), ('FL', 'Freelance')], default='FT', max_length=2)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('application_deadline', models.DateTimeField()),
                ('vacancies', models.IntegerField()),
                ('required_knowledge_skills_abilities', models.TextField()),
                ('education_experience', models.TextField()),
                ('min_experience_years', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.company')),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.location')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.job')),
            ],
        ),
    ]
