# Generated by Django 5.0.1 on 2024-09-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0005_job_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='created_at',
        ),
    ]
