# Generated by Django 5.0.1 on 2024-09-21 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0008_alter_application_applicant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
