# Generated by Django 5.0.1 on 2024-09-21 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0010_application'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
